WINDOW_SIZE_X = 1000
WINDOW_SIZE_Y = 600


;UPDATE BASE_WT_FREQUENCY IF CHANGED
SAMPLING_FREQUENCY = 8100.0
SECTOR_SAMPLE_SIZE = 256
SECTOR_TIME_LENGTH = SAMPLING_FREQUENCY/SECTOR_SAMPLE_SIZE



; UPDATE sequencer.h ON CHANGE!
BUFFER_SIZE_SECTORS =  512

;UPDATE BASE_WT_FREQUENCY IF CHANGED
WAVETABLE_SIZE = 2048
WAVETABLE_SIZE_F = 2048.0

BASE_WT_FREQUENCY = 3.955078125 ;SAMPLING_FREQUENCY/WAVETABLE_SIZE 

BUFFERS_AMOUNT_LOG2 = 3
BUFFERS_AMOUNT equ 6


